name: Discord release notification

on:
  release:
    types: [published]

jobs:
  discord-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send release to Discord
        uses: SethCohen/github-releases-to-discord@v1
        with:
          webhook_url: ${{ secrets.https://discord.com/api/webhooks/1549320069610213426/cQRpFpCdv-M4fDFlz5pZ5kNfoiQbLe-8VTkLimBqA0LLPPMv77C_Nwjl6osgpMwzPhkz }}
          color: "5814783"
          username: "Qaiyo Plugins"
          footer_title: "Teljes changelog"
          footer_url: ${{ github.event.release.html_url }}
          reduce_headings: true
